Django_Level_Four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# need to define app_name to utilize the relative urls with template tagging
# django looks for the global variable 'app_name'
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name = 'relative'),
    url(r'^other/$', views.other, name = 'other'),
    
]

Django_Level_Four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))
]

Django_Level_Four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Django_Level_Four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    context_dict = {
            'text':'hello world',
            'number':100,
    }
    return render(request, 'basic_app/index.html', context = context_dict)

def other(request):

    return render(request, 'basic_app/other.html')

def relative(request):

    return render(request, 'basic_app/relative_url_templates.html')

Django_Level_Four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>

    <nav class = 'navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class = 'nav navbar-nav'>
          <li><a class = 'navbar-brand' href="{% url 'index' %}">BRAND</a></li>
          <li><a class = 'navbar-link' href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class = 'navbar-link' href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>

    </nav>

    <div class="container">
      {% block body_block %}
      <!-- anything outside of this block will be inherited by other templates -->
      {% endblock %}
    </div>

  </body>
</html>

Django_Level_Four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
  <h1>Welcome to index</h1>
  <h1>{{text|upper}}</h1>
  <h1>{{number|add:'5'}}</h1>
{% endblock %}

Django_Level_Four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <h1>Welcome to Other!</h1>
{% endblock %}

Django_Level_Four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <!-- implementing relative urls with template tags -->
    <!-- app_name:name -->
    <a href="{% url 'basic_app:other' %}">OTHER PAGE</a>
    <!-- a link to the admin interface -->
    <a href="{% url 'admin:index' %}">ADMIN interface</a>
    <!-- a link to the index page -->
    <a href="{% url 'index' %}">LINK TO INDEX</a>

  </body>
</html>