Django_Level_Five/learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login')
]

Django_Level_Five/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name = 'logout')
]

Django_Level_Five/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    # to add more attributes to default user model
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional attributes
    portfolio_site = models.URLField(blank = True)
    # all profile pics will be uploaded to the profile_pics dir under media dir
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

Django_Level_Five/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

Django_Level_Five/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
# djanog built-in imports for logging in/out
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # save the form info directly to the database
            user = user_form.save()
            # this method hashes the inputed Password
            # using the hasher specified in settings.py
            user.set_password(user.password)
            user.save()

            # don't save the new profile info to the database just yet
            profile = profile_form.save(commit = False)
            # this sets up the OneToOne relationship between the built-in user model
            # and the additional attributes we gave (check out models.py)
            profile.user = user

            if 'profile_pic' in request.FILES:
                # request.FILES acts like a dictionary of all uploaded files in the form
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.erros, profile_form.errors)
    else:
        # if it is a GET method, set up the forms
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,
                'basic_app/registration.html',
                context = {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered,
                            })

def user_login(request):

    if request.method == 'POST':
        # if the user has filled in the login information

        # get the information from the html form in basic_app/login.html
        username = request.POST.get('username')
        password = request.POST.get('password')

        # this built in django function automatically authenticates a user for you
        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('SOMEONE TRIED TO LOGIN AND FAILED')
            print(f'USERNAME: {username} AND Password: {password}')
            return HttpResponse('INVALID LOGIN DETAILS SUPPLIED ')
    else:
        return render(request, 'basic_app/login.html', context = {})

Django_Level_Five/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class = 'navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class = 'nav navbar-nav'>
          <!-- need to define these URLs in urls.py -->
          <li><a class = 'navbar-brand' href="{% url 'index' %}">HOME</a></li>
          <li><a class = 'navbar-link' href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class = 'navbar-link' href="{% url 'basic_app:register' %}">REGISTER</a></li>

          <!-- logic for the login/logout button -->
          {% if user.is_authenticated %}
            <li><a class = 'navbar-link' href="{% url 'logout'%}">Log Out</a></li>
          {% else %}
            <li><a class = 'navbar-link' href="{% url 'basic_app:user_login'%}">Log In</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>


  </body>
</html>

Django_Level_Five/learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

Django_Level_Five/learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>

  <form action="{% url 'basic_app:user_login'%}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" value="Login">
  </form>

</div>

{% endblock %}

Django_Level_Five/learning_users/templates/basic_app/registration.html
{%extends 'basic_app/base.html' %}
{%load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank You for Registering</h1>

  {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the form</h3>
    <!-- need 'multipart/form-data' to allow for the user to upload different media types-->
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}

      <!-- from our views context dict -->
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class = 'btn btn-primary' value="Register">

    </form>
  {% endif %}
</div>

{% endblock %}